import { Injectable, signal, computed, effect } from '@angular/core';

export type AppLanguage = 'fr' | 'ar';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = signal<AppLanguage>('fr');

  lang = computed(() => this.currentLanguage());
  isArabic = computed(() => this.currentLanguage() === 'ar');

  translations = {
    fr: {
      appName: 'CutCut',
      home: 'Accueil',
      barbers: 'Barbiers',
      bookings: 'Réservations',
      profile: 'Profil',
      login: 'Connexion',
      register: 'Inscription',
      heroBadge: 'RÉSERVATION SIMPLE',
      heroTitle: 'Réservez votre barbier rapidement et sans confusion',
      heroSubtitle: 'Trouvez un barbier, choisissez un créneau, confirmez votre rendez-vous en quelques clics.',
      bookNow: 'Réserver maintenant',
      becomeBarber: 'Devenir barbier',
      fast: 'Rapide',
      fastDesc: 'Réservation en quelques clics',
      simple: 'Simple',
      simpleDesc: 'Une expérience claire pour tous',
      reliable: 'Fiable',
      reliableDesc: 'Gestion réelle des rendez-vous',
      nextAvailable: 'Prochain créneau disponible',
      today: 'Aujourd’hui',
      confirmBooking: 'Confirmer la réservation',
      howItWorks: 'COMMENT ÇA MARCHE',
      howTitle: 'Réserver doit être rapide et évident',
      step1Title: '1. Choisir un barbier',
      step1Desc: 'Parcourez les barbiers disponibles et ouvrez celui qui vous convient.',
      step2Title: '2. Choisir un créneau',
      step2Desc: 'Sélectionnez le jour et l’heure qui vous arrangent.',
      step3Title: '3. Confirmer',
      step3Desc: 'Validez votre réservation et retrouvez-la dans votre espace.',
      featured: 'BARBIERS EN VEDETTE',
      featuredTitle: 'Des professionnels populaires sur CutCut',
      bookThisBarber: 'Réserver ce barbier',
      loginTitle: 'Connexion',
      loginSubtitle: 'Accédez à votre compte pour gérer vos réservations et votre activité.',
      email: 'Email',
      password: 'Mot de passe',
      emailPlaceholder: 'Entrez votre email',
      passwordPlaceholder: 'Entrez votre mot de passe',
      loginButton: 'Se connecter',
      noAccount: 'Vous n’avez pas de compte ?',
      createAccount: 'Créer un compte',
      emailRequired: 'L’email est requis',
      emailInvalid: 'Veuillez entrer un email valide',
      passwordRequired: 'Le mot de passe est requis',
      registerTitle: 'Inscription',
      registerSubtitle: 'Créez votre compte pour réserver ou gérer votre activité de barbier.',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Entrez votre nom complet',
      confirmPassword: 'Confirmer le mot de passe',
      confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
      role: 'Rôle',
      client: 'Client',
      barber: 'Barbier',
      registerButton: 'Créer un compte',
      haveAccount: 'Vous avez déjà un compte ?',
      signIn: 'Se connecter',
      fullNameRequired: 'Le nom complet est requis',
      confirmPasswordRequired: 'La confirmation du mot de passe est requise',
      passwordMismatch: 'Les mots de passe ne correspondent pas',
      roleRequired: 'Le rôle est requis',
      shopName: 'Nom du salon',
      shopNamePlaceholder: 'Entrez le nom du salon',
      city: 'Ville',
      cityPlaceholder: 'Entrez votre ville',
      phone: 'Téléphone',
      phonePlaceholder: 'Entrez votre numéro',
      specialty: 'Spécialité',
      specialtyPlaceholder: 'Ex: Fade, Beard, Coupe classique',
      shopNameRequired: 'Le nom du salon est requis',
      cityRequired: 'La ville est requise',
      phoneRequired: 'Le téléphone est requis',
      specialtyRequired: 'La spécialité est requise',
      clientRegisterSubtitle: 'Créez un compte client pour réserver rapidement vos rendez-vous.',
      barberRegisterSubtitle: 'Créez un compte barbier pour gérer votre activité et vos réservations.',
      barbersTitle: 'Trouvez votre barbier',
      barbersSubtitle: 'Choisissez un professionnel et réservez votre créneau en quelques clics.',
      searchBarber: 'Rechercher un barbier',
      searchPlaceholder: 'Nom, ville ou spécialité',
      allCities: 'Toutes les villes',
      availableBarbers: 'Barbiers disponibles',
      bookAction: 'Réserver',
      viewProfile: 'Voir le profil',
      noBarbersFound: 'Aucun barbier trouvé',
      casablanca: 'Casablanca',
      rabat: 'Rabat',
      marrakech: 'Marrakech',
      fes: 'Fès',
      myReservationsTitle: 'Mes réservations',
      myReservationsSubtitle: 'Retrouvez ici vos rendez-vous à venir et passés.',
      upcomingReservations: 'Réservations à venir',
      pastReservations: 'Réservations passées',
      reservationDate: 'Date',
      reservationTime: 'Heure',
      reservationStatus: 'Statut',
      cancelReservation: 'Annuler',
      noReservations: 'Aucune réservation pour le moment',
      confirmed: 'Confirmée',
      pending: 'En attente',
      cancelled: 'Annulée',
      completed: 'Terminée',  
      profileTitle: 'Mon profil',
      profileSubtitle: 'Gérez vos informations personnelles et votre compte.',
      personalInformation: 'Informations personnelles',
      accountInformation: 'Informations du compte',
      saveChanges: 'Enregistrer les modifications',
      memberSince: 'Membre depuis',
      editProfile: 'Modifier le profil',
      roleClient: 'Client',
      roleBarber: 'Barbier',
      phoneNumber: 'Numéro de téléphone',
      phoneNumberPlaceholder: 'Entrez votre numéro de téléphone',
      cityLabel: 'Ville',
      cityLabelPlaceholder: 'Entrez votre ville',
      profileUpdated: 'Profil mis à jour',
      fullNameMin: 'Le nom doit contenir au moins 2 caractères',
      phoneInvalid: 'Veuillez entrer un numéro valide' ,  
      barberDashboardTitle: 'Tableau de bord barbier',
      barberDashboardSubtitle: 'Suivez votre activité, vos réservations et vos revenus.',
      totalBookings: 'Réservations totales',
      completedBookings: 'Réservations terminées',
      currentBalance: 'Solde actuel',
      commission: 'Commission',
      thisMonth: 'Ce mois-ci',
      upcomingBookingsPreview: 'Prochains rendez-vous',
      viewAllBookings: 'Voir toutes les réservations',
      earningsOverview: 'Aperçu des revenus',
      businessProfile: 'Profil professionnel',
      manageAvailability: 'Gérer la disponibilité',
      commissionNote: 'Commission prélevée sur les réservations confirmées', 
      availabilityTitle: 'Disponibilité',
      availabilitySubtitle: 'Définissez vos jours de travail et vos créneaux horaires.',
      workingDays: 'Jours de travail',
      timeSlots: 'Créneaux horaires',
      addSlot: 'Ajouter un créneau',
      saveAvailability: 'Enregistrer la disponibilité',
      monday: 'Lundi',
      tuesday: 'Mardi',
      wednesday: 'Mercredi',
      thursday: 'Jeudi',
      friday: 'Vendredi',
      saturday: 'Samedi',
      sunday: 'Dimanche',
      morning: 'Matin',
      afternoon: 'Après-midi',
      evening: 'Soir',
      availabilitySaved: 'Disponibilité mise à jour',
      remove: 'Supprimer',
      barberBookingsTitle: 'Réservations reçues',
      barberBookingsSubtitle: 'Consultez les rendez-vous de vos clients et mettez à jour leur statut.',
      clientName: 'Client',
      serviceLabel: 'Service',
      accept: 'Accepter',
      complete: 'Terminer',
      statusUpdated: 'Statut mis à jour',
      allBookings: 'Toutes les réservations',
      todayBookings: 'Aujourd’hui',
      upcomingClients: 'Clients à venir',
      barberProfileTitle: 'Profil barbier',
      barberProfileSubtitle: 'Gérez les informations visibles de votre activité.',
      shopBio: 'Présentation',
      shopBioPlaceholder: 'Décrivez votre salon, vos services et votre style.',
      saveBusinessProfile: 'Enregistrer le profil',
      businessInformation: 'Informations du salon',
      publicProfile: 'Profil public',
      specialtyLabel: 'Spécialité',
      specialtyLabelPlaceholder: 'Ex: Fade, Beard, Coupe classique',
      businessProfileUpdated: 'Profil barbier mis à jour',
      publicPreview: 'Aperçu public',
      barberDetailsTitle: 'Détails du barbier',
      chooseDay: 'Choisir un jour',
      chooseSlot: 'Choisir un créneau',
      confirmReservation: 'Confirmer la réservation',
      aboutBarber: 'À propos',
      bookingSummary: 'Résumé de la réservation',
      selectedDay: 'Jour sélectionné',
      selectedSlot: 'Créneau sélectionné',
      reservationConfirmed: 'Réservation confirmée',
      selectDayFirst: 'Choisissez d’abord un jour',
      selectSlotFirst: 'Choisissez un créneau',
      bookNowAction: 'Réserver maintenant',
      logout: 'Déconnexion',
      dashboard: 'Tableau de bord',
      availabilityNav: 'Disponibilité',
      barberProfileNav: 'Profil barbier',
      notFoundTitle: 'Page introuvable',
      notFoundSubtitle: 'La page que vous cherchez n’existe pas ou a été déplacée.',
      goHome: 'Retour à l’accueil',
      browseBarbers: 'Voir les barbiers',
      price: 'Prix',
      pricePlaceholder: 'Entrez votre prix',
      photoUrlLabel: 'URL de la photo',
      photoUrlPlaceholder: 'Entrez l’URL de votre photo',
      priceRequired: 'Le prix est requis',
      priceInvalid: 'Le prix doit être valide',
      bioRequired: 'La présentation est requise',
      adminDashboardTitle: 'Tableau de bord admin',
      adminDashboardSubtitle: 'Vue globale des utilisateurs, barbiers, réservations et revenus.',
      totalUsersLabel: 'Utilisateurs',
      totalClientsLabel: 'Clients',
      totalBarbersLabel: 'Barbiers',
      totalBookingsLabel: 'Réservations',
      confirmedBookingsLabel: 'Réservations confirmées',
      rejectedBookingsLabel: 'Réservations rejetées',
      totalRevenueLabel: 'Revenu total',
      adminPanel: 'Administration',
        
      
    },
    ar: {
      appName: 'CutCut',
      home: 'الرئيسية',
      barbers: 'الحلاقون',
      bookings: 'الحجوزات',
      profile: 'الملف الشخصي',
      login: 'تسجيل الدخول',
      register: 'إنشاء حساب',
      heroBadge: 'حجز بسيط',
      heroTitle: 'احجز عند الحلاق بسرعة وبدون تعقيد',
      heroSubtitle: 'ابحث عن الحلاق، اختر اليوم والوقت، ثم أكد الموعد في خطوات قليلة.',
      bookNow: 'احجز الآن',
      becomeBarber: 'كن حلاقًا',
      fast: 'سريع',
      fastDesc: 'الحجز في بضع نقرات',
      simple: 'بسيط',
      simpleDesc: 'تجربة واضحة وسهلة للجميع',
      reliable: 'موثوق',
      reliableDesc: 'إدارة حقيقية للمواعيد',
      nextAvailable: 'أقرب موعد متاح',
      today: 'اليوم',
      confirmBooking: 'تأكيد الحجز',
      howItWorks: 'كيف يعمل',
      howTitle: 'يجب أن يكون الحجز سريعًا وواضحًا',
      step1Title: '1. اختر الحلاق',
      step1Desc: 'تصفح الحلاقين المتاحين وافتح من يناسبك.',
      step2Title: '2. اختر الموعد',
      step2Desc: 'حدد اليوم والوقت المناسبين لك.',
      step3Title: '3. أكد',
      step3Desc: 'أكد الحجز وستجده في مساحتك الخاصة.',
      featured: 'حلاقون مميزون',
      featuredTitle: 'محترفون محبوبون على CutCut',
      bookThisBarber: 'احجز هذا الحلاق',
      loginTitle: 'تسجيل الدخول',
      loginSubtitle: 'ادخل إلى حسابك لإدارة حجوزاتك ونشاطك.',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      emailPlaceholder: 'أدخل بريدك الإلكتروني',
      passwordPlaceholder: 'أدخل كلمة المرور',
      loginButton: 'تسجيل الدخول',
      noAccount: 'ليس لديك حساب؟',
      createAccount: 'إنشاء حساب',
      emailRequired: 'البريد الإلكتروني مطلوب',
      emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
      passwordRequired: 'كلمة المرور مطلوبة',
      registerTitle: 'إنشاء حساب',
      registerSubtitle: 'أنشئ حسابك للحجز أو لإدارة نشاطك كحلاق.',
      fullName: 'الاسم الكامل',
      fullNamePlaceholder: 'أدخل اسمك الكامل',
      confirmPassword: 'تأكيد كلمة المرور',
      confirmPasswordPlaceholder: 'أكد كلمة المرور',
      role: 'الدور',
      client: 'عميل',
      barber: 'حلاق',
      registerButton: 'إنشاء حساب',
      haveAccount: 'لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
      fullNameRequired: 'الاسم الكامل مطلوب',
      confirmPasswordRequired: 'تأكيد كلمة المرور مطلوب',
      passwordMismatch: 'كلمتا المرور غير متطابقتين',
      roleRequired: 'الدور مطلوب',
      shopName: 'اسم الصالون',
      shopNamePlaceholder: 'أدخل اسم الصالون',
      city: 'المدينة',
      cityPlaceholder: 'أدخل مدينتك',
      phone: 'الهاتف',
      phonePlaceholder: 'أدخل رقم هاتفك',
      specialty: 'التخصص',
      specialtyPlaceholder: 'مثال: Fade أو Beard أو قصة كلاسيكية',
      shopNameRequired: 'اسم الصالون مطلوب',
      cityRequired: 'المدينة مطلوبة',
      phoneRequired: 'رقم الهاتف مطلوب',
      specialtyRequired: 'التخصص مطلوب',
      clientRegisterSubtitle: 'أنشئ حساب عميل لحجز مواعيدك بسرعة.',
      barberRegisterSubtitle: 'أنشئ حساب حلاق لإدارة نشاطك وحجوزاتك.',
      barbersTitle: 'ابحث عن حلاقك',
      barbersSubtitle: 'اختر الحلاق المناسب واحجز موعدك في بضع خطوات.',
      searchBarber: 'ابحث عن حلاق',
      searchPlaceholder: 'الاسم أو المدينة أو التخصص',
      allCities: 'كل المدن',
      availableBarbers: 'الحلاقون المتاحون',
      bookAction: 'احجز',
      viewProfile: 'عرض الملف',
      noBarbersFound: 'لم يتم العثور على أي حلاق',
      casablanca: 'الدار البيضاء',
      rabat: 'الرباط',
      marrakech: 'مراكش',
      fes: 'فاس',
      myReservationsTitle: 'حجوزاتي',
      myReservationsSubtitle: 'هنا تجد مواعيدك القادمة والسابقة.',
      upcomingReservations: 'الحجوزات القادمة',
      pastReservations: 'الحجوزات السابقة',
      reservationDate: 'التاريخ',
      reservationTime: 'الوقت',
      reservationStatus: 'الحالة',
      cancelReservation: 'إلغاء',
      noReservations: 'لا توجد حجوزات حاليا',
      confirmed: 'مؤكد',
      pending: 'قيد الانتظار',
      cancelled: 'ملغي',
      completed: 'مكتمل',
      profileTitle: 'ملفي الشخصي',
      profileSubtitle: 'قم بإدارة معلوماتك الشخصية وحسابك.',
      personalInformation: 'المعلومات الشخصية',
      accountInformation: 'معلومات الحساب',
      saveChanges: 'حفظ التعديلات',
      memberSince: 'عضو منذ',
      editProfile: 'تعديل الملف الشخصي',
      roleClient: 'عميل',
      roleBarber: 'حلاق',
      phoneNumber: 'رقم الهاتف',
      phoneNumberPlaceholder: 'أدخل رقم هاتفك',
      cityLabel: 'المدينة',
      cityLabelPlaceholder: 'أدخل مدينتك',
      profileUpdated: 'تم تحديث الملف الشخصي',
      fullNameMin: 'يجب أن يحتوي الاسم على حرفين على الأقل',
      phoneInvalid: 'يرجى إدخال رقم هاتف صحيح',
      barberDashboardTitle: 'لوحة تحكم الحلاق',
      barberDashboardSubtitle: 'تابع نشاطك وحجوزاتك وأرباحك.',
      totalBookings: 'إجمالي الحجوزات',
      completedBookings: 'الحجوزات المكتملة',
      currentBalance: 'الرصيد الحالي',
      commission: 'العمولة',
      thisMonth: 'هذا الشهر',
      upcomingBookingsPreview: 'المواعيد القادمة',
      viewAllBookings: 'عرض كل الحجوزات',
      earningsOverview: 'نظرة على الأرباح',
      businessProfile: 'الملف المهني',
      manageAvailability: 'إدارة التوفر',
      commissionNote: 'العمولة المقتطعة من الحجوزات المؤكدة',
      availabilityTitle: 'التوفر',
      availabilitySubtitle: 'حدد أيام العمل والفترات الزمنية المتاحة.',
      workingDays: 'أيام العمل',
      timeSlots: 'الفترات الزمنية',
      addSlot: 'إضافة فترة',
      saveAvailability: 'حفظ التوفر',
      monday: 'الاثنين',
      tuesday: 'الثلاثاء',
      wednesday: 'الأربعاء',
      thursday: 'الخميس',
      friday: 'الجمعة',
      saturday: 'السبت',
      sunday: 'الأحد',
      morning: 'الصباح',
      afternoon: 'بعد الظهر',
      evening: 'المساء',
      availabilitySaved: 'تم تحديث التوفر',
      remove: 'حذف',
      barberBookingsTitle: 'الحجوزات المستلمة',
      barberBookingsSubtitle: 'اطلع على مواعيد زبائنك وقم بتحديث حالتها.',
      clientName: 'العميل',
      serviceLabel: 'الخدمة',
      accept: 'قبول',
      complete: 'إنهاء',
      statusUpdated: 'تم تحديث الحالة',
      allBookings: 'كل الحجوزات',
      todayBookings: 'اليوم',
      upcomingClients: 'الزبائن القادمون',
      barberProfileTitle: 'ملف الحلاق',
      barberProfileSubtitle: 'قم بإدارة المعلومات الظاهرة عن نشاطك.',
      shopBio: 'نبذة',
      shopBioPlaceholder: 'صف صالونك وخدماتك وأسلوبك.',
      saveBusinessProfile: 'حفظ الملف',
      businessInformation: 'معلومات الصالون',
      publicProfile: 'الملف العام',
      specialtyLabel: 'التخصص',
      specialtyLabelPlaceholder: 'مثال: Fade أو Beard أو قصة كلاسيكية',
      businessProfileUpdated: 'تم تحديث ملف الحلاق',
      publicPreview: 'المعاينة العامة',
      barberDetailsTitle: 'تفاصيل الحلاق',
      chooseDay: 'اختر اليوم',
      chooseSlot: 'اختر الفترة',
      confirmReservation: 'تأكيد الحجز',
      aboutBarber: 'نبذة',
      bookingSummary: 'ملخص الحجز',
      selectedDay: 'اليوم المختار',
      selectedSlot: 'الفترة المختارة',
      reservationConfirmed: 'تم تأكيد الحجز',
      selectDayFirst: 'اختر اليوم أولاً',
      selectSlotFirst: 'اختر الفترة',
      bookNowAction: 'احجز الآن',
      logout: 'تسجيل الخروج',
      dashboard: 'لوحة التحكم',
      availabilityNav: 'التوفر',
      barberProfileNav: 'ملف الحلاق',
      notFoundTitle: 'الصفحة غير موجودة',
      notFoundSubtitle: 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
      goHome: 'العودة إلى الرئيسية',
      browseBarbers: 'عرض الحلاقين',
      price: 'السعر',
      pricePlaceholder: 'أدخل السعر',
      photoUrlLabel: 'رابط الصورة',
      photoUrlPlaceholder: 'أدخل رابط الصورة',
      priceRequired: 'السعر مطلوب',
      priceInvalid: 'يجب أن يكون السعر صالحًا',
      bioRequired: 'النبذة مطلوبة',
      adminDashboardTitle: 'لوحة تحكم الإدارة',
      adminDashboardSubtitle: 'نظرة عامة على المستخدمين والحلاقين والحجوزات والإيرادات.',
      totalUsersLabel: 'المستخدمون',
      totalClientsLabel: 'العملاء',
      totalBarbersLabel: 'الحلاقون',
      totalBookingsLabel: 'الحجوزات',
      confirmedBookingsLabel: 'الحجوزات المؤكدة',
      rejectedBookingsLabel: 'الحجوزات المرفوضة',
      totalRevenueLabel: 'إجمالي الإيرادات',
      adminPanel: 'الإدارة',
      


    }
  } as const;

  t = computed(() => this.translations[this.currentLanguage()]);

  constructor() {
    const saved = localStorage.getItem('app_lang') as AppLanguage | null;
    if (saved === 'fr' || saved === 'ar') {
      this.currentLanguage.set(saved);
    }

    effect(() => {
      const lang = this.currentLanguage();
      localStorage.setItem('app_lang', lang);
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    });
  }

  setLanguage(lang: AppLanguage) {
    this.currentLanguage.set(lang);
  }

  toggleLanguage() {
    this.currentLanguage.set(this.currentLanguage() === 'fr' ? 'ar' : 'fr');
  }
}