import { Injectable, signal, computed, effect } from '@angular/core';

export type AppLanguage = 'fr' | 'ar';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = signal<AppLanguage>('fr');

  lang = computed(() => this.currentLanguage());
  isArabic = computed(() => this.currentLanguage() === 'ar');

  translations = {
    fr: {
      appName: 'CutCut',
      home: 'Accueil',
      barbers: 'Barbiers',
      bookings: 'Reservations',
      profile: 'Profil',
      login: 'Connexion',
      register: 'Inscription',
      heroBadge: 'RESERVATION SIMPLE',
      heroTitle: 'Reservez votre barbier rapidement et sans confusion',
      heroSubtitle: 'Trouvez un barbier, choisissez un creneau, confirmez votre rendez-vous en quelques clics.',
      bookNow: 'Reserver maintenant',
      becomeBarber: 'Devenir barbier',
      fast: 'Rapide',
      fastDesc: 'Reservation en quelques clics',
      simple: 'Simple',
      simpleDesc: 'Une experience claire pour tous',
      reliable: 'Fiable',
      reliableDesc: 'Gestion reelle des rendez-vous',
      nextAvailable: 'Prochain creneau disponible',
      today: "Aujourd'hui",
      confirmBooking: 'Confirmer la reservation',
      howItWorks: 'COMMENT CA MARCHE',
      howTitle: 'Reserver doit etre rapide et evident',
      step1Title: '1. Choisir un barbier',
      step1Desc: 'Parcourez les barbiers disponibles et ouvrez celui qui vous convient.',
      step2Title: '2. Choisir un creneau',
      step2Desc: "Selectionnez le jour et l'heure qui vous arrangent.",
      step3Title: '3. Confirmer',
      step3Desc: 'Validez votre reservation et retrouvez-la dans votre espace.',
      featured: 'BARBIERS EN VEDETTE',
      featuredTitle: 'Des professionnels populaires sur CutCut',
      bookThisBarber: 'Reserver ce barbier',
      loginTitle: 'Connexion',
      loginSubtitle: 'Accedez a votre compte pour gerer vos reservations et votre activite.',
      email: 'Email',
      password: 'Mot de passe',
      emailPlaceholder: 'Entrez votre email',
      passwordPlaceholder: 'Entrez votre mot de passe',
      loginButton: 'Se connecter',
      noAccount: "Vous n'avez pas de compte ?",
      createAccount: 'Creer un compte',
      emailRequired: "L'email est requis",
      emailInvalid: 'Veuillez entrer un email valide',
      passwordRequired: 'Le mot de passe est requis',
      registerTitle: 'Inscription',
      registerSubtitle: 'Creez votre compte pour reserver ou gerer votre activite de barbier.',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Entrez votre nom complet',
      confirmPassword: 'Confirmer le mot de passe',
      confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
      role: 'Role',
      client: 'Client',
      barber: 'Barbier',
      registerButton: 'Creer un compte',
      haveAccount: 'Vous avez deja un compte ?',
      signIn: 'Se connecter',
      fullNameRequired: 'Le nom complet est requis',
      confirmPasswordRequired: 'La confirmation du mot de passe est requise',
      passwordMismatch: 'Les mots de passe ne correspondent pas',
      roleRequired: 'Le role est requis',
      shopName: 'Nom du salon',
      shopNamePlaceholder: 'Entrez le nom du salon',
      city: 'Ville',
      cityPlaceholder: 'Entrez votre ville',
      phone: 'Telephone',
      phonePlaceholder: 'Entrez votre numero',
      specialty: 'Specialite',
      specialtyPlaceholder: 'Ex: Fade, Beard, Coupe classique',
      shopNameRequired: 'Le nom du salon est requis',
      cityRequired: 'La ville est requise',
      phoneRequired: 'Le telephone est requis',
      specialtyRequired: 'La specialite est requise',
      clientRegisterSubtitle: 'Creez un compte client pour reserver rapidement vos rendez-vous.',
      barberRegisterSubtitle: 'Creez un compte barbier pour gerer votre activite et vos reservations.',
      barbersTitle: 'Trouvez votre barbier',
      barbersSubtitle: 'Choisissez un professionnel et reservez votre creneau en quelques clics.',
      searchBarber: 'Rechercher un barbier',
      searchPlaceholder: 'Nom, ville ou specialite',
      allCities: 'Toutes les villes',
      availableBarbers: 'Barbiers disponibles',
      bookAction: 'Reserver',
      viewProfile: 'Voir le profil',
      noBarbersFound: 'Aucun barbier trouve',
      casablanca: 'Casablanca',
      rabat: 'Rabat',
      marrakech: 'Marrakech',
      fes: 'Fes',
      myReservationsTitle: 'Mes reservations',
      myReservationsSubtitle: 'Retrouvez ici vos rendez-vous a venir et passes.',
      upcomingReservations: 'Reservations a venir',
      pastReservations: 'Reservations passees',
      reservationDate: 'Date',
      reservationTime: 'Heure',
      reservationStatus: 'Statut',
      cancelReservation: 'Annuler',
      noReservations: 'Aucune reservation pour le moment',
      confirmed: 'Confirmee',
      pending: 'En attente',
      cancelled: 'Annulee',
      completed: 'Terminee',
      profileTitle: 'Mon profil',
      profileSubtitle: 'Gerez vos informations personnelles et votre compte.',
      personalInformation: 'Informations personnelles',
      accountInformation: 'Informations du compte',
      saveChanges: 'Enregistrer les modifications',
      memberSince: 'Membre depuis',
      editProfile: 'Modifier le profil',
      roleClient: 'Client',
      roleBarber: 'Barbier',
      phoneNumber: 'Numero de telephone',
      phoneNumberPlaceholder: 'Entrez votre numero de telephone',
      cityLabel: 'Ville',
      cityLabelPlaceholder: 'Entrez votre ville',
      profileUpdated: 'Profil mis a jour',
      fullNameMin: 'Le nom doit contenir au moins 2 caracteres',
      phoneInvalid: 'Veuillez entrer un numero valide',
      barberDashboardTitle: 'Tableau de bord barbier',
      barberDashboardSubtitle: 'Suivez votre activite, vos reservations et vos revenus.',
      totalBookings: 'Reservations totales',
      completedBookings: 'Reservations terminees',
      currentBalance: 'Solde actuel',
      commission: 'Commission',
      thisMonth: 'Ce mois-ci',
      upcomingBookingsPreview: 'Prochains rendez-vous',
      viewAllBookings: 'Voir toutes les reservations',
      earningsOverview: 'Apercu des revenus',
      businessProfile: 'Profil professionnel',
      manageAvailability: 'Gerer la disponibilite',
      commissionNote: 'Commission prelevee sur les reservations confirmees',
      availabilityTitle: 'Disponibilite',
      availabilitySubtitle: 'Definissez vos jours de travail et vos creneaux horaires.',
      workingDays: 'Jours de travail',
      timeSlots: 'Creneaux horaires',
      addSlot: 'Ajouter un creneau',
      saveAvailability: 'Enregistrer la disponibilite',
      monday: 'Lundi',
      tuesday: 'Mardi',
      wednesday: 'Mercredi',
      thursday: 'Jeudi',
      friday: 'Vendredi',
      saturday: 'Samedi',
      sunday: 'Dimanche',
      morning: 'Matin',
      afternoon: 'Apres-midi',
      evening: 'Soir',
      availabilitySaved: 'Disponibilite mise a jour',
      remove: 'Supprimer',
      barberBookingsTitle: 'Reservations recues',
      barberBookingsSubtitle: 'Consultez les rendez-vous de vos clients et mettez a jour leur statut.',
      clientName: 'Client',
      serviceLabel: 'Service',
      accept: 'Accepter',
      complete: 'Terminer',
      statusUpdated: 'Statut mis a jour',
      allBookings: 'Toutes les reservations',
      todayBookings: "Aujourd'hui",
      upcomingClients: 'Clients a venir',
      barberProfileTitle: 'Profil barbier',
      barberProfileSubtitle: 'Gerez les informations visibles de votre activite.',
      shopBio: 'Presentation',
      shopBioPlaceholder: 'Decrivez votre salon, vos services et votre style.',
      saveBusinessProfile: 'Enregistrer le profil',
      businessInformation: 'Informations du salon',
      publicProfile: 'Profil public',
      specialtyLabel: 'Specialite',
      specialtyLabelPlaceholder: 'Ex: Fade, Beard, Coupe classique',
      businessProfileUpdated: 'Profil barbier mis a jour',
      publicPreview: 'Apercu public',
      barberDetailsTitle: 'Details du barbier',
      chooseDay: 'Choisir un jour',
      chooseSlot: 'Choisir un creneau',
      confirmReservation: 'Confirmer la reservation',
      aboutBarber: 'A propos',
      bookingSummary: 'Resume de la reservation',
      selectedDay: 'Jour selectionne',
      selectedSlot: 'Creneau selectionne',
      reservationConfirmed: 'Reservation confirmee',
      selectDayFirst: "Choisissez d'abord un jour",
      selectSlotFirst: 'Choisissez un creneau',
      bookNowAction: 'Reserver maintenant',
      logout: 'Deconnexion',
      dashboard: 'Tableau de bord',
      availabilityNav: 'Disponibilite',
      barberProfileNav: 'Profil barbier',
      notFoundTitle: 'Page introuvable',
      notFoundSubtitle: "La page que vous cherchez n'existe pas ou a ete deplacee.",
      goHome: "Retour a l'accueil",
      browseBarbers: 'Voir les barbiers',
      price: 'Prix',
      pricePlaceholder: 'Entrez votre prix',
      photoUrlLabel: 'URL de la photo',
      photoUrlPlaceholder: "Entrez l'URL de votre photo",
      priceRequired: 'Le prix est requis',
      priceInvalid: 'Le prix doit etre valide',
      bioRequired: 'La presentation est requise',
      adminDashboardTitle: 'Tableau de bord admin',
      adminDashboardSubtitle: 'Vue globale des utilisateurs, barbiers, reservations et revenus.',
      totalUsersLabel: 'Utilisateurs',
      totalClientsLabel: 'Clients',
      totalBarbersLabel: 'Barbiers',
      totalBookingsLabel: 'Reservations',
      confirmedBookingsLabel: 'Reservations confirmees',
      rejectedBookingsLabel: 'Reservations rejetees',
      totalRevenueLabel: 'Revenu total',
      adminPanel: 'Administration',
      address: 'Adresse',
      photosLabel: 'Photos du salon',
      reviewsLabel: 'Avis clients',
      noReviews: 'Aucun avis pour le moment.',
      noAvailabilityTitle: 'Aucune disponibilite',
      noAvailabilityDesc: "Ce barbier n'a actuellement aucun creneau disponible.",
      openGoogleMaps: 'Ouvrir dans Google Maps',
      chooseServices: 'Choisissez vos services',
      servicesSelected: 'selectionne(s)',
      totalLabel: 'Total',
      reservedSlot: 'Reserve',
      sendMessage: 'Envoyer un message',
      backButton: 'Retour',
      // ✅ Barber Profile Page
      barberProfileSubtitleText: 'Consultez et modifiez les informations de votre activite.',
      changePhoto: 'Changer la photo',
      uploadingPhoto: 'Envoi en cours...',
      nameLabel: 'Nom',
      emailLabel: 'Email',
      phoneLabel: 'Telephone',
      salonLabel: 'Salon',
      priceLabel: 'Prix',
      walletLabel: 'Portefeuille',
      bioLabel: 'Bio',
      addressLabel: 'Adresse',
      clickMapPosition: 'Cliquez sur la carte pour choisir votre position',
      useMyLocationBtn: 'Utiliser ma position',
      locatingBtn: 'Localisation...',
      locationOnMap: 'Localisation sur la carte',
      editBtn: 'Modifier',
      saveBtn: 'Enregistrer',
      cancelBtn: 'Annuler',
      myServices: 'Mes services',
      addServiceBtn: 'Ajouter un service',
      serviceNameLabel: 'Nom du service *',
      servicePriceLabel: 'Prix (DH) *',
      serviceDescLabel: 'Description (optionnel)',
      addBtn: 'Ajouter',
      deleteBtn: 'Supprimer',
      noServiceAdded: 'Aucun service ajoute. Cliquez sur "Ajouter un service" !',
      homeServiceTitle: 'Service a domicile',
      comingSoon: 'Bientot disponible',
      homeServiceDesc: 'Proposez vos services directement chez vos clients',
      comingSoonText: 'Cette fonctionnalite sera disponible prochainement.',
      photosTitle: 'Photos',
      photoDescPlaceholder: 'Description (optionnel)',
      addPhotoBtn: 'Ajouter une photo',
      noPhotos: 'Aucune photo. Ajoutez des photos de votre salon !',
      deletePhoto: 'Supprimer',
    },
    ar: {
      appName: 'CutCut',
      home: 'الرئيسية',
      barbers: 'الحلاقون',
      bookings: 'الحجوزات',
      profile: 'الملف الشخصي',
      login: 'تسجيل الدخول',
      register: 'إنشاء حساب',
      heroBadge: 'حجز بسيط',
      heroTitle: 'احجز عند الحلاق بسرعة وبدون تعقيد',
      heroSubtitle: 'ابحث عن الحلاق، اختر اليوم والوقت، ثم أكد الموعد في خطوات قليلة.',
      bookNow: 'احجز الآن',
      becomeBarber: 'كن حلاقاً',
      fast: 'سريع',
      fastDesc: 'الحجز في بضع نقرات',
      simple: 'بسيط',
      simpleDesc: 'تجربة واضحة وسهلة للجميع',
      reliable: 'موثوق',
      reliableDesc: 'إدارة حقيقية للمواعيد',
      nextAvailable: 'أقرب موعد متاح',
      today: 'اليوم',
      confirmBooking: 'تأكيد الحجز',
      howItWorks: 'كيف يعمل',
      howTitle: 'يجب أن يكون الحجز سريعاً وواضحاً',
      step1Title: '1. اختر الحلاق',
      step1Desc: 'تصفح الحلاقين المتاحين وافتح من يناسبك.',
      step2Title: '2. اختر الموعد',
      step2Desc: 'حدد اليوم والوقت المناسبين لك.',
      step3Title: '3. أكد',
      step3Desc: 'أكد الحجز وستجده في مساحتك الخاصة.',
      featured: 'حلاقون مميزون',
      featuredTitle: 'محترفون محبوبون على CutCut',
      bookThisBarber: 'احجز هذا الحلاق',
      loginTitle: 'تسجيل الدخول',
      loginSubtitle: 'ادخل إلى حسابك لإدارة حجوزاتك ونشاطك.',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      emailPlaceholder: 'أدخل بريدك الإلكتروني',
      passwordPlaceholder: 'أدخل كلمة المرور',
      loginButton: 'تسجيل الدخول',
      noAccount: 'ليس لديك حساب؟',
      createAccount: 'إنشاء حساب',
      emailRequired: 'البريد الإلكتروني مطلوب',
      emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
      passwordRequired: 'كلمة المرور مطلوبة',
      registerTitle: 'إنشاء حساب',
      registerSubtitle: 'أنشئ حسابك للحجز أو لإدارة نشاطك كحلاق.',
      fullName: 'الاسم الكامل',
      fullNamePlaceholder: 'أدخل اسمك الكامل',
      confirmPassword: 'تأكيد كلمة المرور',
      confirmPasswordPlaceholder: 'أكد كلمة المرور',
      role: 'الدور',
      client: 'عميل',
      barber: 'حلاق',
      registerButton: 'إنشاء حساب',
      haveAccount: 'لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
      fullNameRequired: 'الاسم الكامل مطلوب',
      confirmPasswordRequired: 'تأكيد كلمة المرور مطلوب',
      passwordMismatch: 'كلمتا المرور غير متطابقتين',
      roleRequired: 'الدور مطلوب',
      shopName: 'اسم الصالون',
      shopNamePlaceholder: 'أدخل اسم الصالون',
      city: 'المدينة',
      cityPlaceholder: 'أدخل مدينتك',
      phone: 'الهاتف',
      phonePlaceholder: 'أدخل رقم هاتفك',
      specialty: 'التخصص',
      specialtyPlaceholder: 'مثال: Fade أو Beard أو قصة كلاسيكية',
      shopNameRequired: 'اسم الصالون مطلوب',
      cityRequired: 'المدينة مطلوبة',
      phoneRequired: 'رقم الهاتف مطلوب',
      specialtyRequired: 'التخصص مطلوب',
      clientRegisterSubtitle: 'أنشئ حساب عميل لحجز مواعيدك بسرعة.',
      barberRegisterSubtitle: 'أنشئ حساب حلاق لإدارة نشاطك وحجوزاتك.',
      barbersTitle: 'ابحث عن حلاقك',
      barbersSubtitle: 'اختر الحلاق المناسب واحجز موعدك في بضع خطوات.',
      searchBarber: 'ابحث عن حلاق',
      searchPlaceholder: 'الاسم أو المدينة أو التخصص',
      allCities: 'كل المدن',
      availableBarbers: 'الحلاقون المتاحون',
      bookAction: 'احجز',
      viewProfile: 'عرض الملف',
      noBarbersFound: 'لم يتم العثور على أي حلاق',
      casablanca: 'الدار البيضاء',
      rabat: 'الرباط',
      marrakech: 'مراكش',
      fes: 'فاس',
      myReservationsTitle: 'حجوزاتي',
      myReservationsSubtitle: 'هنا تجد مواعيدك القادمة والسابقة.',
      upcomingReservations: 'الحجوزات القادمة',
      pastReservations: 'الحجوزات السابقة',
      reservationDate: 'التاريخ',
      reservationTime: 'الوقت',
      reservationStatus: 'الحالة',
      cancelReservation: 'إلغاء',
      noReservations: 'لا توجد حجوزات حاليا',
      confirmed: 'مؤكد',
      pending: 'قيد الانتظار',
      cancelled: 'ملغى',
      completed: 'مكتمل',
      profileTitle: 'ملفي الشخصي',
      profileSubtitle: 'قم بإدارة معلوماتك الشخصية وحسابك.',
      personalInformation: 'المعلومات الشخصية',
      accountInformation: 'معلومات الحساب',
      saveChanges: 'حفظ التعديلات',
      memberSince: 'عضو منذ',
      editProfile: 'تعديل الملف الشخصي',
      roleClient: 'عميل',
      roleBarber: 'حلاق',
      phoneNumber: 'رقم الهاتف',
      phoneNumberPlaceholder: 'أدخل رقم هاتفك',
      cityLabel: 'المدينة',
      cityLabelPlaceholder: 'أدخل مدينتك',
      profileUpdated: 'تم تحديث الملف الشخصي',
      fullNameMin: 'يجب أن يحتوي الاسم على حرفين على الأقل',
      phoneInvalid: 'يرجى إدخال رقم هاتف صحيح',
      barberDashboardTitle: 'لوحة تحكم الحلاق',
      barberDashboardSubtitle: 'تابع نشاطك وحجوزاتك وأرباحك.',
      totalBookings: 'إجمالي الحجوزات',
      completedBookings: 'الحجوزات المكتملة',
      currentBalance: 'الرصيد الحالي',
      commission: 'العمولة',
      thisMonth: 'هذا الشهر',
      upcomingBookingsPreview: 'المواعيد القادمة',
      viewAllBookings: 'عرض كل الحجوزات',
      earningsOverview: 'نظرة على الأرباح',
      businessProfile: 'الملف المهني',
      manageAvailability: 'إدارة التوفر',
      commissionNote: 'العمولة المقتطعة من الحجوزات المؤكدة',
      availabilityTitle: 'التوفر',
      availabilitySubtitle: 'حدد أيام العمل والفترات الزمنية المتاحة.',
      workingDays: 'أيام العمل',
      timeSlots: 'الفترات الزمنية',
      addSlot: 'إضافة فترة',
      saveAvailability: 'حفظ التوفر',
      monday: 'الاثنين',
      tuesday: 'الثلاثاء',
      wednesday: 'الأربعاء',
      thursday: 'الخميس',
      friday: 'الجمعة',
      saturday: 'السبت',
      sunday: 'الأحد',
      morning: 'الصباح',
      afternoon: 'بعد الظهر',
      evening: 'المساء',
      availabilitySaved: 'تم تحديث التوفر',
      remove: 'حذف',
      barberBookingsTitle: 'الحجوزات المستلمة',
      barberBookingsSubtitle: 'اطلع على مواعيد زبائنك وقم بتحديث حالتها.',
      clientName: 'العميل',
      serviceLabel: 'الخدمة',
      accept: 'قبول',
      complete: 'إنهاء',
      statusUpdated: 'تم تحديث الحالة',
      allBookings: 'كل الحجوزات',
      todayBookings: 'اليوم',
      upcomingClients: 'الزبائن القادمون',
      barberProfileTitle: 'ملف الحلاق',
      barberProfileSubtitle: 'قم بإدارة المعلومات الظاهرة عن نشاطك.',
      shopBio: 'نبذة',
      shopBioPlaceholder: 'صف صالونك وخدماتك وأسلوبك.',
      saveBusinessProfile: 'حفظ الملف',
      businessInformation: 'معلومات الصالون',
      publicProfile: 'الملف العام',
      specialtyLabel: 'التخصص',
      specialtyLabelPlaceholder: 'مثال: Fade أو Beard أو قصة كلاسيكية',
      businessProfileUpdated: 'تم تحديث ملف الحلاق',
      publicPreview: 'المعاينة العامة',
      barberDetailsTitle: 'تفاصيل الحلاق',
      chooseDay: 'اختر اليوم',
      chooseSlot: 'اختر الفترة',
      confirmReservation: 'تأكيد الحجز',
      aboutBarber: 'نبذة',
      bookingSummary: 'ملخص الحجز',
      selectedDay: 'اليوم المختار',
      selectedSlot: 'الفترة المختارة',
      reservationConfirmed: 'تم تأكيد الحجز',
      selectDayFirst: 'اختر اليوم أولاً',
      selectSlotFirst: 'اختر الفترة',
      bookNowAction: 'احجز الآن',
      logout: 'تسجيل الخروج',
      dashboard: 'لوحة التحكم',
      availabilityNav: 'التوفر',
      barberProfileNav: 'ملف الحلاق',
      notFoundTitle: 'الصفحة غير موجودة',
      notFoundSubtitle: 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
      goHome: 'العودة إلى الرئيسية',
      browseBarbers: 'عرض الحلاقين',
      price: 'السعر',
      pricePlaceholder: 'أدخل السعر',
      photoUrlLabel: 'رابط الصورة',
      photoUrlPlaceholder: 'أدخل رابط الصورة',
      priceRequired: 'السعر مطلوب',
      priceInvalid: 'يجب أن يكون السعر صالحاً',
      bioRequired: 'النبذة مطلوبة',
      adminDashboardTitle: 'لوحة تحكم الإدارة',
      adminDashboardSubtitle: 'نظرة عامة على المستخدمين والحلاقين والحجوزات والإيرادات.',
      totalUsersLabel: 'المستخدمون',
      totalClientsLabel: 'العملاء',
      totalBarbersLabel: 'الحلاقون',
      totalBookingsLabel: 'الحجوزات',
      confirmedBookingsLabel: 'الحجوزات المؤكدة',
      rejectedBookingsLabel: 'الحجوزات المرفوضة',
      totalRevenueLabel: 'إجمالي الإيرادات',
      adminPanel: 'الإدارة',
      address: 'العنوان',
      photosLabel: 'صور الصالون',
      reviewsLabel: 'آراء العملاء',
      noReviews: 'لا توجد آراء حتى الآن.',
      noAvailabilityTitle: 'لا توجد مواعيد متاحة',
      noAvailabilityDesc: 'لا يوجد لدى هذا الحلاق أي موعد متاح حالياً.',
      openGoogleMaps: 'فتح في خرائط Google',
      chooseServices: 'اختر خدماتك',
      servicesSelected: 'محدد',
      totalLabel: 'المجموع',
      reservedSlot: 'محجوز',
      sendMessage: 'إرسال رسالة',
      backButton: 'رجوع',
      // ✅ Barber Profile Page
      barberProfileSubtitleText: 'اطلع على معلومات نشاطك وعدّلها.',
      changePhoto: 'تغيير الصورة',
      uploadingPhoto: 'جار الإرسال...',
      nameLabel: 'الاسم',
      emailLabel: 'البريد الإلكتروني',
      phoneLabel: 'الهاتف',
      salonLabel: 'الصالون',
      priceLabel: 'السعر',
      walletLabel: 'المحفظة',
      bioLabel: 'نبذة',
      addressLabel: 'العنوان',
      clickMapPosition: 'انقر على الخريطة لاختيار موقعك',
      useMyLocationBtn: 'استخدام موقعي',
      locatingBtn: 'جار التحديد...',
      locationOnMap: 'الموقع على الخريطة',
      editBtn: 'تعديل',
      saveBtn: 'حفظ',
      cancelBtn: 'إلغاء',
      myServices: 'خدماتي',
      addServiceBtn: 'إضافة خدمة',
      serviceNameLabel: 'اسم الخدمة *',
      servicePriceLabel: 'السعر (DH) *',
      serviceDescLabel: 'وصف (اختياري)',
      addBtn: 'إضافة',
      deleteBtn: 'حذف',
      noServiceAdded: 'لا توجد خدمات. انقر على "إضافة خدمة" !',
      homeServiceTitle: 'الخدمة المنزلية',
      comingSoon: 'قريباً',
      homeServiceDesc: 'قدم خدماتك مباشرة عند عملائك',
      comingSoonText: 'هذه الميزة ستكون متاحة قريباً.',
      photosTitle: 'الصور',
      photoDescPlaceholder: 'وصف (اختياري)',
      addPhotoBtn: 'إضافة صورة',
      noPhotos: 'لا توجد صور. أضف صور صالونك !',
      deletePhoto: 'حذف',
    }
  } as const;

  t = computed(() => this.translations[this.currentLanguage()]);

  constructor() {
    const saved = localStorage.getItem('app_lang') as AppLanguage | null;
    if (saved === 'fr' || saved === 'ar') {
      this.currentLanguage.set(saved);
    }

    effect(() => {
      const lang = this.currentLanguage();
      localStorage.setItem('app_lang', lang);
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    });
  }

  setLanguage(lang: AppLanguage) {
    this.currentLanguage.set(lang);
  }

  toggleLanguage() {
    this.currentLanguage.set(this.currentLanguage() === 'fr' ? 'ar' : 'fr');
  }
}